### ISSUE TITLE
Update install information

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/z3-noodler#92]
The installation guide is not complete. So-far the installation fails on `catch2` things.

**Comment by jurajsic** [comment]
I just had the same problem. We should probably make it an optional dependency, if `catch2` is not found, do not allow building tests.

**Comment by Adda0** [comment]
We need to modify `README-Starexec.md` as follows:
- [ ] Make code coverage optional in Mata (It should already be optional, so maybe just modify the README.)
- [ ] Make compiling Noodler Catch2 tests optional, as we did with Mata, and update the README accordingly.

**Comment by vhavlena** [comment]
In facr in noodler we hade the Catch2 tests optional already before.

**Comment by Adda0** [comment]
It might not be necessary to update install information for Starexec. For further information, see https://github.com/VeriFIT/z3-noodler/pull/101#discussion_r1342351543.
